Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [209]:
import numpy as np

In [210]:
a = np.linspace(12, 24, num = 12, endpoint = False)
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [211]:
a1 = a.reshape(3, 4)
a1

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [212]:
a2 = a.reshape(4, 3)
a2

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [213]:
a3 = a.reshape(2, 6)
a3

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [214]:
a4 = a.reshape(6, 2)
a4

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [215]:
a5 = a.reshape(12, 1)
a5

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [216]:
aa1 = a.reshape(-1, 1)
aa1

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

In [217]:
aa2 = a.reshape(-1,2)
aa2

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [218]:
aa3 = a.reshape(3,-1)
aa3

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [219]:
aa4 = a.reshape(4,-1)
aa4

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [220]:
aa5 = a.reshape(6,-1)
aa5

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? ДА

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [221]:
x = np.random.standard_normal(size=(3,4))
x.mean(), x.std(), x


(-0.3078920875503002,
 0.7652799890738927,
 array([[ 1.40395874, -0.0185508 , -1.67350462, -1.07253183],
        [-0.99258618,  0.10234768, -0.43260928, -0.6591823 ],
        [ 0.0039373 ,  0.4777541 , -0.25902864, -0.57470921]]))

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [222]:
a =np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно 
с интервалом 2. В чем разница между массивами a и b?

In [223]:
b =np.arange(20, 1, -2)
b, a == b # Массивы одинаковые

(array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2]),
 array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]))

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [224]:
a = np.zeros((2,2))
b = np.ones((3,2))
x = np.vstack((a,b))
x.size, a, b, x

(10,
 array([[0., 0.],
        [0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]))

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого 
массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить 
матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью 
матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B 
и почему?

In [225]:
a =np.arange(0, 12, 1)
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [226]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [227]:
B = np.dot(A,At)
x = np.linalg.det(B)
print(B, ', det(B): ',x) 
print('size = ',B.size)
print('Матрица сингулярная, обратной матрицы не существует')

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]] , det(B):  0.0
size =  16
Матрица сингулярная, обратной матрицы не существует


Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [228]:
np.random.seed(42)
np.random.random()

0.3745401188473625

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных 
целых чисел от 0 до 16 невключительно. 

In [229]:
c = np.random.randint(0,16,16)
c

array([12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3,  7])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив 
матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную 
матрицу D_inv для D.

In [230]:
C = c.reshape(4,4)
C

array([[12, 14, 10,  7],
       [12,  4,  6,  9],
       [ 2,  6, 10, 10],
       [ 7,  4,  3,  7]])

In [231]:
D = 10*B + C
D

array([[  62,  154,  240,  327],
       [ 152,  504,  866, 1229],
       [ 232,  866, 1500, 2130],
       [ 327, 1224, 2123, 3027]])

In [232]:
print('определитель: ', round(np.linalg.det(D),2))
print('ранг: ',np.linalg.matrix_rank(D))
print('Обратная матрица: ',np.linalg.inv(D))

определитель:  -2813616.0
ранг:  4
Обратная матрица:  [[-0.02586352  0.0892254  -0.01380643 -0.02371752]
 [ 0.11828195 -0.15369261 -0.10471649  0.12330894]
 [-0.08309663  0.09068402  0.24850939 -0.20270996]
 [ 0.01324559 -0.0110932  -0.13045846  0.09520276]]


Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в 
матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv 
в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны 
соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv 
равен 0, должны быть равны соответствующему элементу матрицы C.

In [233]:
D_inv = np.linalg.inv(D)
D_inv = np.where(D_inv < 0, 0, D_inv)
D_inv = np.where(D_inv > 0, 1, D_inv)
D_inv

array([[0., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.]])

In [234]:
E = np.where(D_inv == 1, B, C)
E

array([[ 12,  14,  10,   7],
       [ 14,   4,   6, 122],
       [  2,  86, 149,  10],
       [ 32,   4,   3, 302]])